services:
  jupyter:
    image: jkropko/legiscan_api
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./:/legiscan_api
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork

volumes:
  postgresdata:
  mongodata:

networks:
  dbnetwork:
